import { chromium, expect, test, type BrowserContext, type Page, type Worker } from '@playwright/test';
import { promises as fs } from 'node:fs';
import http, { type Server } from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const extensionPath = path.resolve(__dirname, '..', '..', 'dist');
const fixturePath = path.resolve(__dirname, 'fixtures', 'selection-page.html');
const expectedSelectionText =
  'Gem Read validates browser selection smoke tests with a stable paragraph so the extension can capture text coordinates and render its overlay deterministically.';

type SelectionResponse = {
  ok: boolean;
  payload?: {
    text: string;
  };
  error?: string;
};

type AnalyzeRequestPayload = {
  text: string;
  mode: string;
  model_name?: string;
  custom_prompt?: string;
  images?: string[];
};

type StubApiState = {
  healthChecks: number;
  modelRequests: number;
  analyzeRequests: AnalyzeRequestPayload[];
};

async function startFixtureServer(): Promise<{ server: Server; url: string }> {
  const html = await fs.readFile(fixturePath, 'utf8');

  return new Promise((resolve, reject) => {
    const server = http.createServer((_request, response) => {
      response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      response.end(html);
    });

    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        reject(new Error('Failed to bind fixture server.'));
        return;
      }

      resolve({
        server,
        url: `http://127.0.0.1:${address.port}`,
      });
    });
  });
}

async function startStubApiServer(): Promise<{ server: Server; url: string; state: StubApiState }> {
  const state: StubApiState = {
    healthChecks: 0,
    modelRequests: 0,
    analyzeRequests: [],
  };

  return new Promise((resolve, reject) => {
    const server = http.createServer(async (request, response) => {
      if (!request.url) {
        response.writeHead(404).end();
        return;
      }

      if (request.method === 'GET' && request.url === '/health') {
        state.healthChecks += 1;
        response.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
        response.end(JSON.stringify({ status: 'ok' }));
        return;
      }

      if (request.method === 'GET' && request.url === '/models') {
        state.modelRequests += 1;
        response.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
        response.end(
          JSON.stringify({
            ok: true,
            models: [
              {
                model_id: 'gemini-2.5-flash',
                display_name: 'Gemini 2.5 Flash',
              },
            ],
            source: 'live',
            availability: 'live',
            detail: null,
            degraded_reason: null,
          }),
        );
        return;
      }

      if (request.method === 'POST' && request.url === '/analyze/translate') {
        let body = '';
        request.setEncoding('utf8');
        request.on('data', (chunk) => {
          body += chunk;
        });
        request.on('end', () => {
          const payload = JSON.parse(body) as AnalyzeRequestPayload;
          state.analyzeRequests.push(payload);
          const translatedText = `[ja] ${payload.text}`;
          const explanation = payload.mode === 'translation_with_explanation'
            ? 'Stub explanation generated by the local API smoke server.'
            : null;
          const rawResponse = explanation
            ? `${translatedText}\n\n---\n\n${explanation}`
            : translatedText;
          response.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
          response.end(
            JSON.stringify({
              ok: true,
              mode: payload.mode,
              translated_text: translatedText,
              explanation,
              raw_response: rawResponse,
              used_mock: false,
              image_count: payload.images?.length ?? 0,
              availability: 'live',
              degraded_reason: null,
              selection_metadata: null,
            }),
          );
        });
        return;
      }

      response.writeHead(404, { 'Content-Type': 'application/json; charset=utf-8' });
      response.end(JSON.stringify({ error: 'not found' }));
    });

    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        reject(new Error('Failed to bind stub API server.'));
        return;
      }

      resolve({
        server,
        url: `http://127.0.0.1:${address.port}`,
        state,
      });
    });
  });
}

async function closeServer(server: Server): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

async function getServiceWorker(context: BrowserContext): Promise<Worker> {
  const existingWorker = context.serviceWorkers()[0];
  if (existingWorker) {
    return existingWorker;
  }

  return context.waitForEvent('serviceworker');
}

async function selectFixtureText(page: Page): Promise<void> {
  await page.locator('#target').waitFor();
  await page.evaluate(() => {
    const paragraph = document.querySelector('#target');
    if (!(paragraph?.firstChild instanceof Text)) {
      throw new Error('Fixture paragraph text node is missing.');
    }

    const range = document.createRange();
    range.setStart(paragraph.firstChild, 0);
    range.setEnd(paragraph.firstChild, paragraph.firstChild.textContent?.length ?? 0);

    const selection = window.getSelection();
    if (!selection) {
      throw new Error('Selection API is unavailable.');
    }

    selection.removeAllRanges();
    selection.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  });
}

async function collectSelection(worker: Worker): Promise<SelectionResponse> {
  return worker.evaluate(async () => {
    const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
    if (!tab?.id) {
      return {
        ok: false,
        error: 'No active tab found.',
      };
    }

    return chrome.tabs.sendMessage(tab.id, {
      type: 'phase0.collectSelection',
      fallbackText: '',
    });
  });
}

async function renderErrorOverlay(worker: Worker, text: string): Promise<void> {
  await worker.evaluate(async (selectedText) => {
    const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
    if (!tab?.id) {
      throw new Error('No active tab found.');
    }

    await chrome.tabs.sendMessage(tab.id, {
      type: 'phase0.renderOverlay',
      payload: {
        status: 'error',
        selectedText,
        error: 'Playwright smoke stub',
      },
    });
  }, text);
}

async function renderPrimedOverlay(worker: Worker, text: string): Promise<void> {
  await worker.evaluate(async (selectedText) => {
    const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
    if (!tab?.id) {
      throw new Error('No active tab found.');
    }

    await chrome.tabs.sendMessage(tab.id, {
      type: 'phase0.renderOverlay',
      payload: {
        status: 'success',
        action: 'translation',
        modelName: 'gemini-2.5-flash',
        modelOptions: [
          {
            modelId: 'gemini-2.5-flash',
            displayName: 'Gemini 2.5 Flash',
          },
        ],
        sessionReady: true,
        selectedText,
        translatedText: 'Primed overlay',
        rawResponse: 'Primed overlay',
      },
    });
  }, text);
}

async function seedOverlaySession(worker: Worker): Promise<void> {
  const response = await worker.evaluate(async () => {
    const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
    if (!tab?.id) {
      throw new Error('No active tab found.');
    }

    return chrome.tabs.sendMessage(tab.id, {
      type: 'phase1.seedOverlaySession',
      payload: {
        previewImageUrl: 'data:image/webp;base64,preview',
        cropDurationMs: 1.5,
        modelOptions: [
          {
            modelId: 'gemini-2.5-flash',
            displayName: 'Gemini 2.5 Flash',
          },
        ],
      },
    });
  });

  expect(response).toMatchObject({ ok: true });
}

async function invokeOverlayAction(worker: Worker): Promise<void> {
  const response = await worker.evaluate(async () => {
    const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
    if (!tab?.id) {
      throw new Error('No active tab found.');
    }

    return chrome.tabs.sendMessage(tab.id, {
      type: 'phase1.invokeOverlayAction',
      payload: {
        action: 'translation_with_explanation',
        modelName: 'gemini-2.5-flash',
      },
    });
  });

  expect(response).toMatchObject({ ok: true });
}

async function getExtensionId(worker: Worker): Promise<string> {
  return new URL(worker.url()).host;
}

async function savePopupSettings(
  context: BrowserContext,
  extensionId: string,
  apiBaseUrl: string,
): Promise<void> {
  const popupPage = await context.newPage();
  await popupPage.goto(`chrome-extension://${extensionId}/index.html`, {
    waitUntil: 'domcontentloaded',
  });
  await popupPage.locator('#api-base-url').fill(apiBaseUrl);
  await popupPage.locator('#default-model').fill('gemini-2.5-flash');
  await popupPage.locator('[data-role="save-button"]').click();

  await expect(popupPage.locator('[data-role="status-badge"]')).toContainText('Reachable');
  await expect(popupPage.locator('[data-role="message-line"]')).toContainText('Settings saved.');
  await popupPage.close();
}

async function readShadowText(page: Page, selector: string): Promise<string | null> {
  return page.locator('#gem-read-phase0-overlay-host').evaluate((host, targetSelector) => {
    return host.shadowRoot?.querySelector(targetSelector)?.textContent ?? null;
  }, selector);
}

test('captures selection and renders the overlay in Chromium', async () => {
  const userDataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'gem-read-extension-'));
  const { server, url } = await startFixtureServer();
  const { server: apiServer, url: apiUrl, state: apiState } = await startStubApiServer();
  let context: BrowserContext | undefined;

  try {
    context = await chromium.launchPersistentContext(userDataDir, {
      channel: 'chromium',
      headless: true,
      args: [
        `--disable-extensions-except=${extensionPath}`,
        `--load-extension=${extensionPath}`,
      ],
    });

    const worker = await getServiceWorker(context);
    const extensionId = await getExtensionId(worker);
    await savePopupSettings(context, extensionId, apiUrl);

    const page = await context.newPage();
    await page.goto(url, { waitUntil: 'domcontentloaded' });
    await expect(page.locator('#target')).toContainText('Gem Read validates browser selection smoke tests');
    await selectFixtureText(page);

    await expect.poll(async () => {
      const response = await collectSelection(worker);
      return response.ok ? response.payload?.text ?? '' : '';
    }).toBe(expectedSelectionText);

    const response = await collectSelection(worker);
    expect(response).toMatchObject({
      ok: true,
      payload: {
        text: expectedSelectionText,
      },
    });

    await renderErrorOverlay(worker, response.payload?.text ?? expectedSelectionText);

    await expect.poll(async () => readShadowText(page, '.selection-box')).toBe(expectedSelectionText);
    await expect.poll(async () => readShadowText(page, '.error-box')).toBe('Playwright smoke stub');

    await seedOverlaySession(worker);
    await renderPrimedOverlay(worker, response.payload?.text ?? expectedSelectionText);
    await expect.poll(async () => readShadowText(page, '.result-box')).toBe('Primed overlay');

    await invokeOverlayAction(worker);

    await expect.poll(async () => readShadowText(page, '.badge')).toContain('Live Result');
    await expect.poll(async () => readShadowText(page, '.result-box')).toBe(`[ja] ${expectedSelectionText}`);
    await expect.poll(async () => readShadowText(page, '.explanation-box')).toBe(
      'Stub explanation generated by the local API smoke server.',
    );

    expect(apiState.healthChecks).toBeGreaterThan(0);
    expect(apiState.modelRequests).toBeGreaterThan(0);
    expect(apiState.analyzeRequests).toHaveLength(1);
    expect(apiState.analyzeRequests[0]).toMatchObject({
      mode: 'translation_with_explanation',
      text: expectedSelectionText,
      model_name: 'gemini-2.5-flash',
    });
  } finally {
    await context?.close();
    await closeServer(server);
    await closeServer(apiServer);
    await fs.rm(userDataDir, { recursive: true, force: true });
  }
});